### ISSUE TITLE
Inverted sections rendered incorrectly for existing values

### ISSUE THREAD

**Issue by kyrel** [vspy/scala-mustache#2]
## This block of code in SectionToken.render:

```
    case str:String => StringProduct(str)

    case other =>
      composite(children, other, partials, callstack)
```

---

does not check if the section is inverted or not so it should better be

case str:String => if (!inverted) StringProduct(str) else EmptyProduct
case other =>  if(!inverted) composite(children, other, partials, callstack) else EmptyProduct

**Comment by vspy** [comment]
fixed
