### ISSUE TITLE
Update for scala-2.10

### ISSUE THREAD

**Issue by laughedelic** [vspy/scala-mustache#4]
Hello,
I'd like to use your library for a project on scala-2.10. It looks like your code builds with it, but tests don't work, because of old `specs` version (and for newer version some code changes are needed).
So could your update the project for using latest sbt-0.12 and scala-2.10?

**Comment by vspy** [comment]
Please try new version from master, let me know if something is still not OK.

**Comment by laughedelic** [comment]
Thanks! now it compiles and passes all tests. The only thing is that there are some warnings about type erasure in matching:

```
[warn] .../scala-mustache/src/main/scala/Mustache.scala:432: non-variable type argument String in type pattern String => _ is unchecked since it is eliminated by erasure
[warn]         case f:Function1[String, _] =>
[warn]                ^
[warn] .../scala-mustache/src/main/scala/Mustache.scala:435: non-variable type argument String in type pattern (String, String => String) => _ is unchecked since it is eliminated by erasure
[warn]         case f:Function2[String, Function1[String,String], _] =>
[warn]                ^
...
```

I don't know if this is a proper solution, but I have this workaround for such cases:

``` scala
type F1[t] = Function1[String, t]
type F2[t] = Function2[String, Function1[String,String], t] 
//...
case f:F1[_] => //...
case f:F2[_] => //...
```

what do you think about it?

P.S. I also wanted to ask you to publish artifacts somewhere, so that I could use this library as a managed dependency through sbt... Could you do it for me?

**Comment by jedesah** [comment]
This issue should be closed. The title is upgrade to Scala 2.10. The project is now using Scala 2.11.1.

Hopefully side issues have been resolved by now, if not, then maybe another issue should be opened.

**Comment by vspy** [comment]
Thanks, closing it
